DROP DATABASE IF EXISTS research_management_db;
CREATE DATABASE research_management_db;
USE research_management_db;

CREATE TABLE User (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT chk_email_format CHECK (email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'),
    CONSTRAINT chk_password_strength CHECK (password REGEXP '^[A-Za-z0-9@#\\-_$%^&+=]{6,}$')
);

CREATE TABLE Student (
    student_id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cgpa DECIMAL(3, 2),
    department VARCHAR(100),
    semester VARCHAR(50),
    github_link VARCHAR(255),
    cv_link VARCHAR(255),
    FOREIGN KEY (student_id) REFERENCES User(user_id) ON DELETE CASCADE
);

CREATE TABLE Faculty (
    faculty_id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    designation VARCHAR(100),
    department VARCHAR(100),
    office_hours VARCHAR(255),
    FOREIGN KEY (faculty_id) REFERENCES User(user_id) ON DELETE CASCADE
);

CREATE TABLE Research_Project (
    project_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    required_skill TEXT,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    applicant_count INT DEFAULT 0,
    faculty_id INT NOT NULL,
    FOREIGN KEY (faculty_id) REFERENCES Faculty(faculty_id) ON DELETE CASCADE
);

CREATE TABLE Application (
    project_id INT NOT NULL,
    application_id INT NOT NULL,
    student_id INT NOT NULL,
    cover_letter TEXT,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50),
    PRIMARY KEY (project_id, application_id),
    FOREIGN KEY (project_id) REFERENCES Research_Project(project_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES Student(student_id) ON DELETE CASCADE
);

CREATE TABLE Student_Skills (
    student_id INT NOT NULL,
    skill VARCHAR(100) NOT NULL,
    PRIMARY KEY (student_id, skill),
    FOREIGN KEY (student_id) REFERENCES Student(student_id) ON DELETE CASCADE
);

CREATE TABLE Faculty_Research_Areas (
    faculty_id INT NOT NULL,
    research_area VARCHAR(150) NOT NULL,
    PRIMARY KEY (faculty_id, research_area),
    FOREIGN KEY (faculty_id) REFERENCES Faculty(faculty_id) ON DELETE CASCADE
);

CREATE INDEX idx_application_student ON Application(student_id);

CREATE VIEW Active_Projects_View AS
SELECT project_id, title, status 
FROM Research_Project;

INSERT INTO User (user_id, email, password, role) VALUES
(1, 'student1@cse.uiu.ac.bd', 'CSE-Std#1', 'Student'),
(2, 'student2@cse.uiu.ac.bd', 'CSE-Std#2', 'Student'),
(3, 'student3@cse.uiu.ac.bd', 'CSE-Std#3', 'Student'),
(4, 'student4@cse.uiu.ac.bd', 'CSE-Std#4', 'Student'),
(5, 'student5@cse.uiu.ac.bd', 'CSE-Std#5', 'Student'),
(6, 'student1@eee.uiu.ac.bd', 'EEE-Std#1', 'Student'),
(7, 'student2@eee.uiu.ac.bd', 'EEE-Std#2', 'Student'),
(8, 'student3@eee.uiu.ac.bd', 'EEE-Std#3', 'Student'),
(9, 'student4@eee.uiu.ac.bd', 'EEE-Std#4', 'Student'),
(10, 'student5@eee.uiu.ac.bd', 'EEE-Std#5', 'Student'),
(11, 'student1@me.uiu.ac.bd', 'ME-Std-123', 'Student'),
(12, 'student2@me.uiu.ac.bd', 'ME-Std-456', 'Student'),
(13, 'student3@me.uiu.ac.bd', 'ME-Std-789', 'Student'),
(14, 'student4@me.uiu.ac.bd', 'ME-Std-321', 'Student'),
(15, 'student5@me.uiu.ac.bd', 'ME-Std-654', 'Student'),
(16, 'student1@ce.uiu.ac.bd', 'CE-Pass_1', 'Student'),
(17, 'student2@ce.uiu.ac.bd', 'CE-Pass_2', 'Student'),
(18, 'student3@ce.uiu.ac.bd', 'CE-Pass_3', 'Student'),
(19, 'student4@ce.uiu.ac.bd', 'CE-Pass_4', 'Student'),
(20, 'student5@ce.uiu.ac.bd', 'CE-Pass_5', 'Student'),
(21, 'student1@bme.uiu.ac.bd', 'BME-Secure1', 'Student'),
(22, 'student2@bme.uiu.ac.bd', 'BME-Secure2', 'Student'),
(23, 'student3@bme.uiu.ac.bd', 'BME-Secure3', 'Student'),
(24, 'student4@bme.uiu.ac.bd', 'BME-Secure4', 'Student'),
(25, 'student5@bme.uiu.ac.bd', 'BME-Secure5', 'Student'),
(26, 'student1@mse.uiu.ac.bd', 'MSE-Key#1', 'Student'),
(27, 'student2@mse.uiu.ac.bd', 'MSE-Key#2', 'Student'),
(28, 'student3@mse.uiu.ac.bd', 'MSE-Key#3', 'Student'),
(29, 'student4@mse.uiu.ac.bd', 'MSE-Key#4', 'Student'),
(30, 'student5@mse.uiu.ac.bd', 'MSE-Key#5', 'Student'),
(31, 'faculty1@cse.uiu.ac.bd', 'Prof-CSE#1', 'Faculty'),
(32, 'faculty2@cse.uiu.ac.bd', 'Prof-CSE#2', 'Faculty'),
(33, 'faculty3@cse.uiu.ac.bd', 'Prof-CSE#3', 'Faculty'),
(34, 'faculty4@cse.uiu.ac.bd', 'Prof-CSE#4', 'Faculty'),
(35, 'faculty5@cse.uiu.ac.bd', 'Prof-CSE#5', 'Faculty'),
(36, 'faculty1@eee.uiu.ac.bd', 'Prof-EEE#1', 'Faculty'),
(37, 'faculty2@eee.uiu.ac.bd', 'Prof-EEE#2', 'Faculty'),
(38, 'faculty3@eee.uiu.ac.bd', 'Prof-EEE#3', 'Faculty'),
(39, 'faculty4@eee.uiu.ac.bd', 'Prof-EEE#4', 'Faculty'),
(40, 'faculty5@eee.uiu.ac.bd', 'Prof-EEE#5', 'Faculty'),
(41, 'faculty1@me.uiu.ac.bd', 'Prof-ME-111', 'Faculty'),
(42, 'faculty2@me.uiu.ac.bd', 'Prof-ME-222', 'Faculty'),
(43, 'faculty3@me.uiu.ac.bd', 'Prof-ME-333', 'Faculty'),
(44, 'faculty4@me.uiu.ac.bd', 'Prof-ME-444', 'Faculty'),
(45, 'faculty5@me.uiu.ac.bd', 'Prof-ME-555', 'Faculty'),
(46, 'faculty1@ce.uiu.ac.bd', 'Prof-CE_01', 'Faculty'),
(47, 'faculty2@ce.uiu.ac.bd', 'Prof-CE_02', 'Faculty'),
(48, 'faculty3@ce.uiu.ac.bd', 'Prof-CE_03', 'Faculty'),
(49, 'faculty4@ce.uiu.ac.bd', 'Prof-CE_04', 'Faculty'),
(50, 'faculty5@ce.uiu.ac.bd', 'Prof-CE_05', 'Faculty'),
(51, 'faculty1@bme.uiu.ac.bd', 'Doc-BME#1', 'Faculty'),
(52, 'faculty2@bme.uiu.ac.bd', 'Doc-BME#2', 'Faculty'),
(53, 'faculty3@bme.uiu.ac.bd', 'Doc-BME#3', 'Faculty'),
(54, 'faculty4@bme.uiu.ac.bd', 'Doc-BME#4', 'Faculty'),
(55, 'faculty5@bme.uiu.ac.bd', 'Doc-BME#5', 'Faculty'),
(56, 'faculty1@mse.uiu.ac.bd', 'Doc-MSE#1', 'Faculty'),
(57, 'faculty2@mse.uiu.ac.bd', 'Doc-MSE#2', 'Faculty'),
(58, 'faculty3@mse.uiu.ac.bd', 'Doc-MSE#3', 'Faculty'),
(59, 'faculty4@mse.uiu.ac.bd', 'Doc-MSE#4', 'Faculty'),
(60, 'faculty5@mse.uiu.ac.bd', 'Doc-MSE#5', 'Faculty'),
(61, 'admin1@uiu.ac.bd', 'Root-Admin#1', 'admin'),
(62, 'admin2@uiu.ac.bd', 'Root-Admin#2', 'admin'),
(63, 'admin3@uiu.ac.bd', 'Root-Admin#3', 'admin'),
(64, 'admin4@uiu.ac.bd', 'Root-Admin#4', 'admin'),
(65, 'admin5@uiu.ac.bd', 'Root-Admin#5', 'admin');

INSERT INTO Student (student_id, name, cgpa, department, semester, github_link, cv_link) VALUES
(1, 'Student CSE 1', 3.85, 'CSE', '8th', 'https://github.com/s1', 'https://cv.com/1'),
(2, 'Student CSE 2', 3.75, 'CSE', '7th', 'https://github.com/s2', 'https://cv.com/2'),
(3, 'Student CSE 3', 3.90, 'CSE', '6th', 'https://github.com/s3', 'https://cv.com/3'),
(4, 'Student CSE 4', 3.65, 'CSE', '5th', 'https://github.com/s4', 'https://cv.com/4'),
(5, 'Student CSE 5', 3.80, 'CSE', '8th', 'https://github.com/s5', 'https://cv.com/5'),
(6, 'Student EEE 1', 3.70, 'EEE', '7th', 'https://github.com/s6', 'https://cv.com/6'),
(7, 'Student EEE 2', 3.82, 'EEE', '8th', 'https://github.com/s7', 'https://cv.com/7'),
(8, 'Student EEE 3', 3.55, 'EEE', '6th', 'https://github.com/s8', 'https://cv.com/8'),
(9, 'Student EEE 4', 3.91, 'EEE', '5th', 'https://github.com/s9', 'https://cv.com/9'),
(10, 'Student EEE 5', 3.60, 'EEE', '8th', 'https://github.com/s10', 'https://cv.com/10'),
(11, 'Student ME 1', 3.72, 'Mechanical Engineering', '6th', 'https://github.com/s11', 'https://cv.com/11'),
(12, 'Student ME 2', 3.88, 'Mechanical Engineering', '7th', 'https://github.com/s12', 'https://cv.com/12'),
(13, 'Student ME 3', 3.45, 'Mechanical Engineering', '5th', 'https://github.com/s13', 'https://cv.com/13'),
(14, 'Student ME 4', 3.79, 'Mechanical Engineering', '8th', 'https://github.com/s14', 'https://cv.com/14'),
(15, 'Student ME 5', 3.68, 'Mechanical Engineering', '6th', 'https://github.com/s15', 'https://cv.com/15'),
(16, 'Student CE 1', 3.81, 'Civil Engineering', '8th', 'https://github.com/s16', 'https://cv.com/16'),
(17, 'Student CE 2', 3.59, 'Civil Engineering', '7th', 'https://github.com/s17', 'https://cv.com/17'),
(18, 'Student CE 3', 3.94, 'Civil Engineering', '6th', 'https://github.com/s18', 'https://cv.com/18'),
(19, 'Student CE 4', 3.67, 'Civil Engineering', '5th', 'https://github.com/s19', 'https://cv.com/19'),
(20, 'Student CE 5', 3.74, 'Civil Engineering', '8th', 'https://github.com/s20', 'https://cv.com/20'),
(21, 'Student BME 1', 3.89, 'Biomedical Engineering', '7th', 'https://github.com/s21', 'https://cv.com/21'),
(22, 'Student BME 2', 3.52, 'Biomedical Engineering', '6th', 'https://github.com/s22', 'https://cv.com/22'),
(23, 'Student BME 3', 3.77, 'Biomedical Engineering', '8th', 'https://github.com/s23', 'https://cv.com/23'),
(24, 'Student BME 4', 3.83, 'Biomedical Engineering', '5th', 'https://github.com/s24', 'https://cv.com/24'),
(25, 'Student BME 5', 3.61, 'Biomedical Engineering', '7th', 'https://github.com/s25', 'https://cv.com/25'),
(26, 'Student MSE 1', 3.92, 'Materials Science', '8th', 'https://github.com/s26', 'https://cv.com/26'),
(27, 'Student MSE 2', 3.66, 'Materials Science', '6th', 'https://github.com/s27', 'https://cv.com/27'),
(28, 'Student MSE 3', 3.73, 'Materials Science', '7th', 'https://github.com/s28', 'https://cv.com/28'),
(29, 'Student MSE 4', 3.80, 'Materials Science', '5th', 'https://github.com/s29', 'https://cv.com/29'),
(30, 'Student MSE 5', 3.58, 'Materials Science', '8th', 'https://github.com/s30', 'https://cv.com/30');

INSERT INTO Faculty (faculty_id, name, designation, department, office_hours) VALUES
(31, 'Dr. Faculty CSE 1', 'Professor', 'CSE', 'Sun-Tue 10:00 AM'),
(32, 'Dr. Faculty CSE 2', 'Associate Professor', 'CSE', 'Mon-Wed 11:00 AM'),
(33, 'Dr. Faculty CSE 3', 'Assistant Professor', 'CSE', 'Sun-Thu 02:00 PM'),
(34, 'Mr. Faculty CSE 4', 'Lecturer', 'CSE', 'Sat-Mon 09:00 AM'),
(35, 'Mr. Faculty CSE 5', 'Senior Lecturer', 'CSE', 'Tue-Wed 01:00 PM'),
(36, 'Dr. Faculty EEE 1', 'Professor', 'EEE', 'Sun-Wed 10:00 AM'),
(37, 'Dr. Faculty EEE 2', 'Associate Professor', 'EEE', 'Mon-Thu 12:00 PM'),
(38, 'Dr. Faculty EEE 3', 'Assistant Professor', 'EEE', 'Sun-Tue 03:00 PM'),
(39, 'Mr. Faculty EEE 4', 'Lecturer', 'EEE', 'Sat-Wed 10:00 AM'),
(40, 'Mr. Faculty EEE 5', 'Senior Lecturer', 'EEE', 'Sun-Thu 11:00 AM'),
(41, 'Dr. Faculty ME 1', 'Professor', 'Mechanical Engineering', 'Mon-Wed 02:00 PM'),
(42, 'Dr. Faculty ME 2', 'Associate Professor', 'Mechanical Engineering', 'Sun-Thu 10:00 AM'),
(43, 'Dr. Faculty ME 3', 'Assistant Professor', 'Mechanical Engineering', 'Sat-Mon 11:00 AM'),
(44, 'Mr. Faculty ME 4', 'Lecturer', 'Mechanical Engineering', 'Sun-Tue 01:00 PM'),
(45, 'Mr. Faculty ME 5', 'Senior Lecturer', 'Mechanical Engineering', 'Tue-Wed 03:00 PM'),
(46, 'Dr. Faculty CE 1', 'Professor', 'Civil Engineering', 'Sun-Wed 09:00 AM'),
(47, 'Dr. Faculty CE 2', 'Associate Professor', 'Civil Engineering', 'Mon-Thu 02:00 PM'),
(48, 'Dr. Faculty CE 3', 'Assistant Professor', 'Civil Engineering', 'Sat-Mon 10:00 AM'),
(49, 'Mr. Faculty CE 4', 'Lecturer', 'Civil Engineering', 'Sun-Tue 11:00 AM'),
(50, 'Mr. Faculty CE 5', 'Senior Lecturer', 'Civil Engineering', 'Tue-Wed 02:00 PM'),
(51, 'Dr. Faculty BME 1', 'Professor', 'Biomedical Engineering', 'Sun-Thu 10:00 AM'),
(52, 'Dr. Faculty BME 2', 'Associate Professor', 'Biomedical Engineering', 'Mon-Wed 11:00 AM'),
(53, 'Dr. Faculty BME 3', 'Assistant Professor', 'Biomedical Engineering', 'Sat-Tue 01:00 PM'),
(54, 'Mr. Faculty BME 4', 'Lecturer', 'Biomedical Engineering', 'Sun-Wed 03:00 PM'),
(55, 'Mr. Faculty BME 5', 'Senior Lecturer', 'Biomedical Engineering', 'Mon-Thu 09:00 AM'),
(56, 'Dr. Faculty MSE 1', 'Professor', 'Materials Science', 'Sun-Tue 11:00 AM'),
(57, 'Dr. Faculty MSE 2', 'Associate Professor', 'Materials Science', 'Mon-Wed 02:00 PM'),
(58, 'Dr. Faculty MSE 3', 'Assistant Professor', 'Materials Science', 'Sat-Thu 10:00 AM'),
(59, 'Mr. Faculty MSE 4', 'Lecturer', 'Materials Science', 'Sun-Wed 01:00 PM'),
(60, 'Mr. Faculty MSE 5', 'Senior Lecturer', 'Materials Science', 'Tue-Thu 03:00 PM');

INSERT INTO Student_Skills (student_id, skill) VALUES
(1, 'Python'), (1, 'Machine Learning'), (1, 'Networking'),
(2, 'Python'), (2, 'Data Structures'), (2, 'SQL'), (2, 'Git'),
(3, 'C++'), (3, 'Algorithms'), (3, 'Java'),
(4, 'Java'), (4, 'Spring Boot'), (4, 'SQL'),
(5, 'Python'), (5, 'Deep Learning'), (5, 'PyTorch'), (5, 'NLP'),
(6, 'Python'), (6, 'IoT'), (6, 'Circuit Design'),
(7, 'MATLAB'), (7, 'Signal Processing'), (7, 'Simulink'),
(8, 'C++'), (8, 'Embedded Systems'),
(9, 'Python'), (9, 'Power Systems'), (9, 'Electrical Safety'),
(10, 'Verilog'), (10, 'FPGA'),
(11, 'C++'), (11, 'Robotics'), (11, 'CAD'), (11, 'ROS'),
(12, 'ANSYS'), (12, 'Thermodynamics'),
(13, 'SolidWorks'), (13, 'Machine Design'), (13, 'AutoCAD'),
(14, 'Python'), (14, 'Fluid Dynamics'),
(15, 'MATLAB'), (15, 'Kinematics'), (15, 'Dynamics'),
(16, 'Python'), (16, 'Data Analysis'), (16, 'AutoCAD'), (16, 'Statistics'),
(17, 'STAAD.Pro'), (17, 'Structural Analysis'),
(18, 'Revit'), (18, 'Surveying'), (18, 'Estimation'),
(19, 'Concrete Tech'), (19, 'Geotech'),
(20, 'Python'), (20, 'GIS Mapping'), (20, 'ArcGIS'),
(21, 'Python'), (21, 'Signal Processing'), (21, 'Biomedical Sensors'),
(22, 'LabVIEW'), (22, 'Biomechanics'),
(23, 'MATLAB'), (23, 'Medical Imaging'), (23, 'Image Processing'),
(24, 'C++'), (24, 'Bioinformatics'),
(25, 'Python'), (25, 'Neural Engineering'), (25, 'Statistics'),
(26, 'Python'), (26, 'Materials Characterization'), (26, 'Nanotech'), (26, 'Chemistry'),
(27, 'SEM Analysis'), (27, 'Polymer Science'),
(28, 'XRD'), (28, 'Metallurgy'), (28, 'Material Testing'),
(29, 'C++'), (29, 'Crystal Growth'),
(30, 'Python'), (30, 'Composite Materials'), (30, 'Nanomaterials');

INSERT INTO Faculty_Research_Areas (faculty_id, research_area) VALUES
(31, 'Network Security'), (31, 'Machine Learning'),
(32, 'Artificial Intelligence'), (32, 'Data Science'), (32, 'NLP'),
(33, 'Cybersecurity'), (33, 'Blockchain'),
(34, 'Software Engineering'), (34, 'Web Tech'),
(35, 'Cloud Computing'), (35, 'Distributed Systems'), (35, 'Edge Computing'),
(36, 'Smart Grid'), (36, 'Renewable Energy'),
(37, 'Power Electronics'), (37, 'Control Systems'),
(38, 'VLSI Design'), (38, 'Nanotechnology'),
(39, 'Robotics'), (39, 'Automation'),
(40, 'Wireless Communication'), (40, 'IoT'), (40, '5G Networks'),
(41, 'Thermal Engineering'), (41, 'Fluid Mechanics'),
(42, 'Mechatronics'), (42, 'Robotics'),
(43, 'Automotive Systems'), (43, 'Dynamics'),
(44, 'HVAC'), (44, 'Energy Systems'),
(45, 'Manufacturing'), (45, 'CAD/CAM'), (45, '3D Printing'),
(46, 'Structural Engineering'), (46, 'Earthquake Engineering'),
(47, 'Geotechnical Engineering'), (47, 'Soil Mechanics'),
(48, 'Transportation Engineering'), (48, 'Highway Design'),
(49, 'Environmental Engineering'), (49, 'Water Resources'),
(50, 'Construction Management'), (50, 'Project Planning'), (50, 'BIM'),
(51, 'Biomedical Signal Processing'), (51, 'Neural Engineering'),
(52, 'Medical Imaging'), (52, 'Biomaterials'),
(53, 'Biomechanics'), (53, 'Tissue Engineering'),
(54, 'Bioinformatics'), (54, 'Genomics'),
(55, 'Biosensors'), (55, 'Nanomedicine'), (55, 'Microfluidics'),
(56, 'Advanced Materials'), (56, 'Nanomaterials'),
(57, 'Metallurgy'), (57, 'Corrosion Science'),
(58, 'Polymer Chemistry'), (58, 'Composite Materials'),
(59, 'Electronic Materials'), (59, 'Semiconductors'),
(60, 'Ceramics'), (60, 'Surface Science');

INSERT INTO Research_Project (project_id, title, description, required_skill, status, applicant_count, faculty_id) VALUES
(1, 'ML in Network Security', 'Detecting anomalies in high-speed networks.', 'Python, ML', 'Active', 2, 31),
(2, 'Zero-Day Vulnerability Analysis', 'Predicting software vulnerabilities.', 'Python, Security', 'Active', 1, 31),
(3, 'AI Threat Intelligence', 'Threat detection with deep learning.', 'Python, PyTorch', 'Active', 0, 31),
(4, 'Deep Fake Detection', 'Identifying manipulated media files.', 'Python, Deep Learning', 'Active', 3, 32),
(5, 'Conversational Clinical Agents', 'NLP bots for preliminary triage.', 'Python, NLP', 'Active', 2, 32),
(6, 'Smart Contract Auditing', 'Automated security checks for Solidity.', 'Solidity, Security', 'Active', 1, 33),
(7, 'Decentralized Identity Frameworks', 'Self-sovereign identity design.', 'Blockchain, Cryptography', 'Active', 0, 33),
(8, 'Agile Metrics Predictor', 'Predicting software release bugs.', 'Java, Statistics', 'Active', 2, 34),
(9, 'Serverless Cost Optimization', 'Cloud function efficiency modeling.', 'Cloud, Python', 'Active', 1, 35),
(10, 'Edge Computing Offloading', 'Task scheduling in fog networks.', 'C++, Networking', 'Active', 2, 35),
(11, 'Smart Grid Frequency Control', 'Renewable integration stability.', 'MATLAB, Control Systems', 'Active', 3, 36),
(12, 'Solar Farm Fault Diagnostics', 'IoT-based panel monitoring.', 'IoT, Python', 'Active', 0, 36),
(13, 'Electric Vehicle Powertrain', 'Inverter efficiency optimization.', 'Power Electronics', 'Active', 1, 37),
(14, 'Low-Power VLSI Architectures', 'Energy-efficient chip design.', 'Verilog, FPGA', 'Active', 2, 38),
(15, 'Autonomous Delivery Drones', 'Path planning in urban canyons.', 'C++, ROS', 'Active', 1, 39),
(16, '5G Massive MIMO Optimization', 'Beamforming algorithm design.', 'MATLAB, Wireless', 'Active', 2, 40),
(17, 'IoT Industrial Sensor Networks', 'Reliable industrial automation.', 'IoT, C++', 'Active', 0, 40),
(18, 'Microfluidic Heat Exchangers', 'Cooling high-power electronics.', 'ANSYS, Thermal', 'Active', 1, 41),
(19, 'Exoskeleton Joint Kinematics', 'Assistive tech for mobility.', 'SolidWorks, Kinematics', 'Active', 3, 42),
(20, 'Autonomous Vehicle Suspension', 'Active damping controllers.', 'MATLAB, Control', 'Active', 2, 43),
(21, 'Building Energy Simulation', 'HVAC load forecasting.', 'Python, Thermodynamics', 'Active', 0, 44),
(22, 'Additive Manufacturing Toolpaths', 'Optimizing 3D printing layers.', 'CAD, CAM', 'Active', 1, 45),
(23, 'Seismic Retrofitting of Bridges', 'Ductility analysis under load.', 'STAAD.Pro, Structural', 'Active', 2, 46),
(24, 'High-Rise Wind Load Analysis', 'CFD simulation of skyscrapers.', 'ANSYS, Fluid Dynamics', 'Active', 1, 46),
(25, 'Liquefaction Hazard Mapping', 'Soil behavior during earthquakes.', 'Geotech, Soil Mechanics', 'Active', 0, 47),
(26, 'Smart Traffic Corridor Design', 'Signal timing optimization.', 'GIS Mapping, Traffic', 'Active', 2, 48),
(27, 'Urban Wastewater Bioremediation', 'Filtering heavy metals.', 'Environmental, Chemistry', 'Active', 1, 49),
(28, 'BIM-based Safety Monitoring', 'Real-time hazard detection on site.', 'Revit, Python', 'Active', 3, 50),
(29, 'EEG Signal Classification', 'BCI for motor imagery.', 'Python, Signal Processing', 'Active', 2, 51),
(30, 'Neural Spike Sorting', 'Unsupervised clustering of neurons.', 'Python, Neural Networks', 'Active', 1, 51),
(31, 'MRI Segmentation with AI', 'Tumor boundary identification.', 'Python, Medical Imaging', 'Active', 0, 52),
(32, 'Bone Scaffold Biocompatibility', '3D printed porous implants.', 'Biomaterials, CAD', 'Active', 2, 53),
(33, 'Proteomic Sequence Alignment', 'Fast alignment algorithms.', 'C++, Bioinformatics', 'Active', 1, 54),
(34, 'Point-of-Care Biosensors', 'Microfluidic pathogen detection.', 'Biosensors, LabVIEW', 'Active', 2, 55),
(35, 'Advanced Malware Analysis', 'Reverse engineering unknown binaries.', 'Assembly, C++', 'Active', 1, 31),
(36, 'Quantum Key Distribution Simulator', 'Simulating QKD networks.', 'Python, Cryptography', 'Active', 2, 32),
(37, 'Smart Microgrid Protection', 'Relay coordination using AI.', 'MATLAB, Power Systems', 'Active', 0, 36),
(38, 'Autonomous Mobile Robots', 'SLAM mapping and localization.', 'ROS, C++', 'Active', 2, 39),
(39, 'Composite Material Fatigue Life', 'Cyclic loading analysis.', 'Materials Science', 'Active', 1, 46),
(40, 'Cardiovascular Flow Simulations', 'Blood flow dynamics in stents.', 'ANSYS, Biomedical', 'Active', 2, 51);

INSERT INTO Application (project_id, application_id, student_id, cover_letter, status) VALUES
(1, 1, 1, 'Strong interest in network security.', 'Pending'),
(1, 2, 2, 'Eager to contribute to anomaly detection.', 'Pending'),
(2, 1, 1, 'Familiar with vulnerability scoring.', 'Pending'),
(4, 1, 3, 'Experienced in computer vision.', 'Pending'),
(4, 2, 5, 'Passionate about deep learning.', 'Pending'),
(4, 3, 2, 'Ready to work on image forensics.', 'Pending'),
(5, 1, 4, 'Interested in NLP conversational agents.', 'Pending'),
(5, 2, 1, 'Background in text processing.', 'Pending'),
(6, 1, 3, 'Solid blockchain background.', 'Pending'),
(8, 1, 4, 'Skilled in Java and data systems.', 'Pending'),
(8, 2, 2, 'Familiar with bug metrics.', 'Pending'),
(9, 1, 5, 'Cloud optimization enthusiast.', 'Pending'),
(10, 1, 1, 'Edge computing research interest.', 'Pending'),
(10, 2, 3, 'C++ systems programmer.', 'Pending'),
(11, 1, 6, 'Smart grid researcher.', 'Pending'),
(11, 2, 9, 'Power systems background.', 'Pending'),
(11, 3, 7, 'MATLAB specialist.', 'Pending'),
(13, 1, 8, 'Power electronics coursework done.', 'Pending'),
(14, 1, 10, 'FPGA design experience.', 'Pending'),
(14, 2, 8, 'Verilog coding skills.', 'Pending'),
(15, 1, 11, 'Robotics and ROS background.', 'Pending'),
(16, 1, 7, 'Wireless communication focus.', 'Pending'),
(16, 2, 9, 'Interested in MIMO systems.', 'Pending'),
(18, 1, 12, 'ANSYS thermal simulation expert.', 'Pending'),
(19, 1, 11, 'Kinematics project experience.', 'Pending'),
(19, 2, 15, 'SolidWorks CAD designer.', 'Pending'),
(19, 3, 12, 'Mechatronics enthusiast.', 'Pending'),
(20, 1, 15, 'Active suspension modeling interest.', 'Pending'),
(20, 2, 11, 'Control systems background.', 'Pending'),
(22, 1, 13, 'SolidWorks and manufacturing focus.', 'Pending'),
(23, 1, 16, 'Structural analysis skills.', 'Pending'),
(23, 2, 17, 'STAAD.Pro certified.', 'Pending'),
(24, 1, 18, 'Revit and structural design.', 'Pending'),
(26, 1, 20, 'GIS mapping specialist.', 'Pending'),
(26, 2, 16, 'Data analysis background.', 'Pending'),
(27, 1, 19, 'Environmental engineering major.', 'Pending'),
(28, 1, 18, 'BIM workflow knowledge.', 'Pending'),
(28, 2, 16, 'Python safety script developer.', 'Pending'),
(28, 3, 20, 'Geospatial site mapping.', 'Pending'),
(29, 1, 21, 'Signal processing research interest.', 'Pending'),
(29, 2, 25, 'Neural engineering background.', 'Pending'),
(30, 1, 21, 'Python spike sorting scripts.', 'Pending'),
(32, 1, 22, 'Biomaterials coursework.', 'Pending'),
(32, 2, 23, 'Medical imaging experience.', 'Pending'),
(33, 1, 24, 'Bioinformatics algorithms in C++.', 'Pending'),
(34, 1, 25, 'Biosensor lab assistant.', 'Pending'),
(34, 2, 22, 'LabVIEW programming skill.', 'Pending'),
(35, 1, 26, 'Nanotechnology interest.', 'Pending'),
(37, 1, 27, 'Polymer science research assistant.', 'Pending'),
(37, 2, 28, 'Materials lab experience.', 'Pending'),
(38, 1, 29, 'Semiconductor crystal growth.', 'Pending'),
(39, 1, 30, 'Composite materials background.', 'Pending'),
(39, 2, 26, 'Materials characterization skill.', 'Pending'),
(40, 1, 21, 'Cardiovascular flow simulation interest.', 'Pending'),
(40, 2, 22, 'Fluid modeling background.', 'Pending');
